### ISSUE TITLE
Game suggestions/story/characters/gameplay

### ISSUE THREAD

**Issue by Cocomomilkshake** [Cocomomilkshake/javaprogramsbyme#1]
(credit goes to abdullah)
story: 
hamza milk farm empire is thriving on it's business, until someday the sk ib di bop nikacado avacado empire takes over hamza milk farm's place as the number one milk seller, so the player has to be the army general(on hamza milk farm empire's side) leading an army provided by the hamza milk farm empire, the player has to destroy all of sk bi di bop nikacado avacado empire milk farms through out the ****empire, just like da EIC****(lore check), and this is where the player would encounter rival armies(a game just like battle cats) and u have to fight them through, each one of the armies will be protecting one of the farms of the sk bi di bop nikacado avacado empire(just call it skibini empire), the player will have to destroy all of them to win the game and be the new leader of hamza milk farm empire.

(credit to me, these my ideas)
enemies:
i have got some ideas for enemies, so we have 3 bosses:
- shariqi da mole star(u see what i did abdullah?)
- ayaan da black lung(u get da black lung by defeating him, this allows u to create black smoke to hinder sights of enemies)
- azmah(hamza spelled backwards, aka i am big brain) the emperor of the skibini empire (game ends after defeating him).

i have some dealers:
- ahmed da bomber(u get the idea, he sells bombs)
- ali the weapnsmith(he sells btr swords for ur men, this medival times so no guns boi)
- hamza the emperor of the hamza milk farm empire(u buy troops from him).
- hannah the crazy witch(potions, dont have any idea what potions cuz dis post already too long rn lol).

**Comment by gutsxgriffith** [comment]
lets make a game about how shariq met edp

**Comment by Cocomomilkshake** [comment]
(credit goes to abdullah)
story: 
hamza milk farm empire is thriving on it's business, until someday the sk ib di bop nikacado avacado empire takes over hamza milk farm's place as the number one milk seller, so the player has to be the army general(on hamza milk farm empire's side) leading an army provided by the hamza milk farm empire, the player has to destroy all of sk bi di bop nikacado avacado empire milk farms through out the ****empire, just like da EIC****(lore check), and this is where the player would encounter rival armies(a game just like battle cats) and u have to fight them through, each one of the armies will be protecting one of the farms of the sk bi di bop nikacado avacado empire(just call it skibini empire), the player will have to destroy all of them to win the game and be the new leader of hamza milk farm empire.

(credit to me, these my ideas)
enemies:
i have got some ideas for enemies, so we have 3 bosses:
- shariqi da mole star(u see what i did abdullah?)
- ayaan da black lung(u get da black lung by defeating him, this allows u to create black smoke to hinder sights of enemies)
- azmah(hamza spelled backwards, aka i am big brain) the emperor of the skibini empire (game ends after defeating him).

i have some dealers:
- ahmed da bomber(u get the idea, he sells bombs)
- ali the weapnsmith(he sells btr swords for ur men, this medival times so no guns boi)
- hamza the emperor of the hamza milk farm empire(u buy troops from him).
- hannah the crazy witch(potions, dont have any idea what potions cuz dis post already too long rn lol).

**Comment by Cocomomilkshake** [comment]
> (credit goes to abdullah) story: hamza milk farm empire is thriving on it's business, until someday the sk ib di bop nikacado avacado empire takes over hamza milk farm's place as the number one milk seller, so the player has to be the army general(on hamza milk farm empire's side) leading an army provided by the hamza milk farm empire, the player has to destroy all of sk bi di bop nikacado avacado empire milk farms through out the **empire, just like da EIC**(lore check), and this is where the player would encounter rival armies(a game just like battle cats) and u have to fight them through, each one of the armies will be protecting one of the farms of the sk bi di bop nikacado avacado empire(just call it skibini empire), the player will have to destroy all of them to win the game and be the new leader of hamza milk farm empire.
> 
> (credit to me, these my ideas) enemies: i have got some ideas for enemies, so we have 3 bosses:
> 
> * shariqi da mole star(u see what i did abdullah?)
> * ayaan da black lung(u get da black lung by defeating him, this allows u to create black smoke to hinder sights of enemies)
> * azmah(hamza spelled backwards, aka i am big brain) the emperor of the skibini empire (game ends after defeating him).
> 
> i have some dealers:
> 
> * ahmed da bomber(u get the idea, he sells bombs)
> * ali the weapnsmith(he sells btr swords for ur men, this medival times so no guns boi)
> * hamza the emperor of the hamza milk farm empire(u buy troops from him).
> * hannah the crazy witch(potions, dont have any idea what potions cuz dis post already too long rn lol).

**Comment by gutsxgriffith** [comment]
> (credit goes to abdullah) story: hamza milk farm empire is thriving on it's business, until someday the sk ib di bop nikacado avacado empire takes over hamza milk farm's place as the number one milk seller, so the player has to be the army general(on hamza milk farm empire's side) leading an army provided by the hamza milk farm empire, the player has to destroy all of sk bi di bop nikacado avacado empire milk farms through out the **empire, just like da EIC**(lore check), and this is where the player would encounter rival armies(a game just like battle cats) and u have to fight them through, each one of the armies will be protecting one of the farms of the sk bi di bop nikacado avacado empire(just call it skibini empire), the player will have to destroy all of them to win the game and be the new leader of hamza milk farm empire.
> 
> (credit to me, these my ideas) enemies: i have got some ideas for enemies, so we have 3 bosses:
> 
> * shariqi da mole star(u see what i did abdullah?)
> * ayaan da black lung(u get da black lung by defeating him, this allows u to create black smoke to hinder sights of enemies)
> * azmah(hamza spelled backwards, aka i am big brain) the emperor of the skibini empire (game ends after defeating him).
> 
> i have some dealers:
> 
> * ahmed da bomber(u get the idea, he sells bombs)
> * ali the weapnsmith(he sells btr swords for ur men, this medival times so no guns boi)
> * hamza the emperor of the hamza milk farm empire(u buy troops from him).
> * hannah the crazy witch(potions, dont have any idea what potions cuz dis post already too long rn lol).

damn thats crazy! very good ideaas

**Comment by Cocomomilkshake** [comment]
> > (credit goes to abdullah) story: hamza milk farm empire is thriving on it's business, until someday the sk ib di bop nikacado avacado empire takes over hamza milk farm's place as the number one milk seller, so the player has to be the army general(on hamza milk farm empire's side) leading an army provided by the hamza milk farm empire, the player has to destroy all of sk bi di bop nikacado avacado empire milk farms through out the **empire, just like da EIC**(lore check), and this is where the player would encounter rival armies(a game just like battle cats) and u have to fight them through, each one of the armies will be protecting one of the farms of the sk bi di bop nikacado avacado empire(just call it skibini empire), the player will have to destroy all of them to win the game and be the new leader of hamza milk farm empire.
> > (credit to me, these my ideas) enemies: i have got some ideas for enemies, so we have 3 bosses:
> > 
> > * shariqi da mole star(u see what i did abdullah?)
> > * ayaan da black lung(u get da black lung by defeating him, this allows u to create black smoke to hinder sights of enemies)
> > * azmah(hamza spelled backwards, aka i am big brain) the emperor of the skibini empire (game ends after defeating him).
> > 
> > i have some dealers:
> > 
> > * ahmed da bomber(u get the idea, he sells bombs)
> > * ali the weapnsmith(he sells btr swords for ur men, this medival times so no guns boi)
> > * hamza the emperor of the hamza milk farm empire(u buy troops from him).
> > * hannah the crazy witch(potions, dont have any idea what potions cuz dis post already too long rn lol).
> 
> damn thats crazy! very good ideaas

thxx

**Comment by gutsxgriffith** [comment]
> (credit goes to abdullah) story: hamza milk farm empire is thriving on it's business, until someday the sk ib di bop nikacado avacado empire takes over hamza milk farm's place as the number one milk seller, so the player has to be the army general(on hamza milk farm empire's side) leading an army provided by the hamza milk farm empire, the player has to destroy all of sk bi di bop nikacado avacado empire milk farms through out the **empire, just like da EIC**(lore check), and this is where the player would encounter rival armies(a game just like battle cats) and u have to fight them through, each one of the armies will be protecting one of the farms of the sk bi di bop nikacado avacado empire(just call it skibini empire), the player will have to destroy all of them to win the game and be the new leader of hamza milk farm empire.
> 
> (credit to me, these my ideas) enemies: i have got some ideas for enemies, so we have 3 bosses:
> 
> * shariqi da mole star(u see what i did abdullah?)
> * ayaan da black lung(u get da black lung by defeating him, this allows u to create black smoke to hinder sights of enemies)
> * azmah(hamza spelled backwards, aka i am big brain) the emperor of the skibini empire (game ends after defeating him).
> 
> i have some dealers:
> 
> * ahmed da bomber(u get the idea, he sells bombs)
> * ali the weapnsmith(he sells btr swords for ur men, this medival times so no guns boi)
> * hamza the emperor of the hamza milk farm empire(u buy troops from him).
> * hannah the crazy witch(potions, dont have any idea what potions cuz dis post already too long rn lol).

so will these be like a pokemon game or smth like rpg or option like game

**Comment by Cocomomilkshake** [comment]
> > (credit goes to abdullah) story: hamza milk farm empire is thriving on it's business, until someday the sk ib di bop nikacado avacado empire takes over hamza milk farm's place as the number one milk seller, so the player has to be the army general(on hamza milk farm empire's side) leading an army provided by the hamza milk farm empire, the player has to destroy all of sk bi di bop nikacado avacado empire milk farms through out the **empire, just like da EIC**(lore check), and this is where the player would encounter rival armies(a game just like battle cats) and u have to fight them through, each one of the armies will be protecting one of the farms of the sk bi di bop nikacado avacado empire(just call it skibini empire), the player will have to destroy all of them to win the game and be the new leader of hamza milk farm empire.
> > (credit to me, these my ideas) enemies: i have got some ideas for enemies, so we have 3 bosses:
> > 
> > * shariqi da mole star(u see what i did abdullah?)
> > * ayaan da black lung(u get da black lung by defeating him, this allows u to create black smoke to hinder sights of enemies)
> > * azmah(hamza spelled backwards, aka i am big brain) the emperor of the skibini empire (game ends after defeating him).
> > 
> > i have some dealers:
> > 
> > * ahmed da bomber(u get the idea, he sells bombs)
> > * ali the weapnsmith(he sells btr swords for ur men, this medival times so no guns boi)
> > * hamza the emperor of the hamza milk farm empire(u buy troops from him).
> > * hannah the crazy witch(potions, dont have any idea what potions cuz dis post already too long rn lol).
> 
> so will these be like a pokemon game or smth like rpg or option like game

like u have to select what u gonna do, like ur troops

**Comment by gutsxgriffith** [comment]
Thats goated story tbh one day Insha'Allah we will make this
